# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge, bioconda, r
          environment-file: tests/env.yml
          channel-priority: true
          activate-environment: test-autoplier
      - name: Set up env
        run: |
          conda activate test-autoplier
          export RETICULATE_PYTHON=$(which python)
          echo $RETICULATE_PYTHON
          echo "RETICULATE_PYTHON=$(which python)" >> $GITHUB_ENV
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: any::rcmdcheck
      - name: Set up env
        run: |
          echo $RETICULATE_PYTHON
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran", "--no-build-vignettes")'
          build_args: 'c("--no-build-vignettes")'
          error-on: '"error"'
          check-dir: '"check"'
      - name: Test coverage
        if: github.ref == 'refs/heads/main'
        run: |
          install.packages("covr")
          covr::codecov()
        shell: Rscript {0}
